### ISSUE TITLE
请问如何兼容10.0呢？

### ISSUE THREAD

**Issue by dev-lz-67345** [xuexiangjys/XUpdateAPI#15]

**Comment by dev-lz-67345** [comment]
我再Android10.0上用的时候出现以下错误，导致界面提示"解析软件包时出现问题"：
05-07 11:27:45.172  7072  7098 W InstallStaging: java.lang.SecurityException: Permission Denial: opening provider com.xuexiang.xupdate.utils.UpdateFileProvider from ProcessRecord{52d2bf7 7072:com.android.packageinstaller/u0a16} (pid=7072, uid=10016) that is not exported from UID 1000
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.os.Parcel.createException(Parcel.java:2071)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.os.Parcel.readException(Parcel.java:2039)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.os.Parcel.readException(Parcel.java:1987)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5054)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6561)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2725)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2117)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1671)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at com.android.packageinstaller.InstallStaging$StagingAsyncTask.doInBackground(InstallStaging.java:174)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at com.android.packageinstaller.InstallStaging$StagingAsyncTask.doInBackground(InstallStaging.java:167)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.os.AsyncTask$3.call(AsyncTask.java:378)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at java.lang.Thread.run(Thread.java:919)
05-07 11:27:45.172  7072  7098 W InstallStaging: Caused by: android.os.RemoteException: Remote stack trace:
05-07 11:27:45.172  7072  7098 W InstallStaging:        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:6885)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7305)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2078)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2752)
05-07 11:27:45.172  7072  7098 W InstallStaging:        at android.os.Binder.execTransactInternal(Binder.java:1021)
05-07 11:27:45.172  7072  7098 W InstallStaging:

**Comment by dev-lz-67345** [comment]
我的应用需要在清单文件中配置android:sharedUserId="android.uid.system"
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:sharedUserId="android.uid.system"
    package="com.demo.demoapp">

**Comment by dev-lz-67345** [comment]
将android:exported="false" 报错：
05-07 09:39:23.876 10545 10581 W InstallStaging: java.lang.SecurityException: Permission Denial: opening provider com.xuexiang.xupdate.utils.UpdateFileProvider from ProcessRecord{2074f1d 10545:com.android.packageinstaller/u0a16} (pid=10545, uid=10016) that is not exported from UID 1000

将android:exported="true" 报错：
User Permission Denial: opening provider com.demo.demo.CustomFileProvider from ProcessRecord{498c4ba 25514:com.android.packageinstaller/u0a16} (pid=25514, uid=10016) that is not exported from UID 1000
 java.lang.SecurityException: Provider must not be exported

**Comment by dev-lz-67345** [comment]
可以了。按教程自定义实现安装器即可。
https://github.com/xuexiangjys/XUpdate/blob/master/README_ZH.md
如果你的apk安装与众不同，你可以实现自己的apk安装器。你只需要实现OnInstallListener接口，并通过XUpdate.setOnInstallListener进行设置即可生效。

**Comment by dev-lz-67345** [comment]
安装方式：
https://stackoverflow.com/questions/59105199/how-to-install-any-android-app-programmatically-in-android-10
